# Generated by Django 3.2.3 on 2021-10-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='imagesfun',
            field=models.ImageField(default='', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.CharField(default='', max_length=200),
        ),
    ]
